///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesNikleShoes = 'assets/images/nikle_shoes.webp';
  static const String imagesPorganic = 'assets/images/porganic.png';
  static const String imagesPorganic01 = 'assets/images/porganic01.png';

}
