///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String iconsLight = 'assets/icons/light.svg';
  static const String iconsLight1 = 'assets/icons/light1.svg';
  static const String iconsLight2 = 'assets/icons/light2.svg';
  static const String imagesLamp = 'assets/images/lamp.png';
  static const String imagesNikleShoes = 'assets/images/nikle_shoes.webp';
  static const String imagesPorganic = 'assets/images/porganic.png';
  static const String imagesPorganic01 = 'assets/images/porganic01.png';
  static const String imagesSwitchOff = 'assets/images/switch_off.png';
  static const String imagesSwitchOn = 'assets/images/switch_on.png';


}
